// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE104_AirlineTicketManage.Server.Data;

#nullable disable

namespace SE104_AirlineTicketManage.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240501060238_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBay", b =>
                {
                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSB_Den")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSB_Di")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianBay")
                        .HasColumnType("int");

                    b.HasKey("MaCB");

                    b.ToTable("ChuyenBays");

                    b.HasData(
                        new
                        {
                            MaCB = "CB01",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB02",
                            MaSB_Di = "SB01",
                            NgayGio = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBayHangVe", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHV", "MaCB");

                    b.HasIndex("MaCB");

                    b.ToTable("ChuyenBayHangVes");

                    b.HasData(
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB01",
                            SoLuong = 100
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.HangVe", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TiLe_Gia")
                        .HasColumnType("float");

                    b.HasKey("MaHV");

                    b.ToTable("HangVes");

                    b.HasData(
                        new
                        {
                            MaHV = "HV01",
                            TenHV = "Hang thuong gia",
                            TiLe_Gia = 1.5
                        },
                        new
                        {
                            MaHV = "HV02",
                            TenHV = "Hang pho thong",
                            TiLe_Gia = 1.0
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            MaKH = "KH01",
                            CMND = "123456789",
                            SDT = "0123456789",
                            TenKH = "Nguyen Van A"
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.QuyDinhChung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ThoiGianChamNhatDatVe")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianHuyDatVe")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("QuyDinhChungs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ThoiGianChamNhatDatVe = 30,
                            ThoiGianHuyDatVe = 3
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBay", b =>
                {
                    b.Property<string>("MaSB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TGDungMax")
                        .HasColumnType("int");

                    b.Property<int>("TGDungMin")
                        .HasColumnType("int");

                    b.Property<string>("TenSB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSB");

                    b.ToTable("SanBays");

                    b.HasData(
                        new
                        {
                            MaSB = "SB01",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Noi Bai",
                            ViTri = "Ha Noi"
                        },
                        new
                        {
                            MaSB = "SB02",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Tan Son Nhat",
                            ViTri = "Ho Chi Minh"
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBayTrungGian", b =>
                {
                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TGDung")
                        .HasColumnType("int");

                    b.HasKey("MaCB", "MaSB");

                    b.HasIndex("MaSB");

                    b.ToTable("SanBayTrungGians");

                    b.HasData(
                        new
                        {
                            MaCB = "CB01",
                            MaSB = "SB01",
                            GhiChu = "Ghi chu 1",
                            TGDung = 45
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SoSanBayDung", b =>
                {
                    b.Property<string>("MaSanBayDi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSanBayDen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoSBDung_Max")
                        .HasColumnType("int");

                    b.HasKey("MaSanBayDi", "MaSanBayDen");

                    b.ToTable("SoSanBayDungs");

                    b.HasData(
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB02",
                            SoSBDung_Max = 1
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.VeMayBay", b =>
                {
                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaCB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVe");

                    b.HasIndex("MaCB");

                    b.HasIndex("MaHV");

                    b.HasIndex("MaKH");

                    b.ToTable("VeMayBays");

                    b.HasData(
                        new
                        {
                            MaVe = "VMB01",
                            GiaTien = 1500000m,
                            MaCB = "CB01",
                            MaHV = "HV01",
                            MaKH = "KH01",
                            NgayDat = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayMua = new DateTime(2021, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Da mua"
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBayHangVe", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("ChuyenBayHangVes")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.HangVe", "HangVe")
                        .WithMany("ChuyenBayHangVes")
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("HangVe");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBayTrungGian", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("SanBayTrungGians")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.SanBay", "SanBay")
                        .WithMany("SanBayTrungGians")
                        .HasForeignKey("MaSB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("SanBay");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.VeMayBay", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("VeMayBays")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.HangVe", "HangVe")
                        .WithMany("VeMayBays")
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.KhachHang", "KhachHang")
                        .WithMany("VeMayBays")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("HangVe");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBay", b =>
                {
                    b.Navigation("ChuyenBayHangVes");

                    b.Navigation("SanBayTrungGians");

                    b.Navigation("VeMayBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.HangVe", b =>
                {
                    b.Navigation("ChuyenBayHangVes");

                    b.Navigation("VeMayBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.KhachHang", b =>
                {
                    b.Navigation("VeMayBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBay", b =>
                {
                    b.Navigation("SanBayTrungGians");
                });
#pragma warning restore 612, 618
        }
    }
}
