// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE104_AirlineTicketManage.Server.Data;

#nullable disable

namespace SE104_AirlineTicketManage.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBay", b =>
                {
                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSB_Den")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSB_Di")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianBay")
                        .HasColumnType("int");

                    b.HasKey("MaCB");

                    b.ToTable("ChuyenBays");

                    b.HasData(
                        new
                        {
                            MaCB = "CB01",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB02",
                            MaSB_Di = "SB01",
                            NgayGio = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        },
                        new
                        {
                            MaCB = "CB02",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB03",
                            MaSB_Di = "SB02",
                            NgayGio = new DateTime(2021, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        },
                        new
                        {
                            MaCB = "CB03",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB04",
                            MaSB_Di = "SB03",
                            NgayGio = new DateTime(2021, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        },
                        new
                        {
                            MaCB = "CB04",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB05",
                            MaSB_Di = "SB04",
                            NgayGio = new DateTime(2021, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        },
                        new
                        {
                            MaCB = "CB05",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB06",
                            MaSB_Di = "SB05",
                            NgayGio = new DateTime(2021, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        },
                        new
                        {
                            MaCB = "CB06",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB07",
                            MaSB_Di = "SB06",
                            NgayGio = new DateTime(2021, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        },
                        new
                        {
                            MaCB = "CB07",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB08",
                            MaSB_Di = "SB07",
                            NgayGio = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        },
                        new
                        {
                            MaCB = "CB08",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB09",
                            MaSB_Di = "SB08",
                            NgayGio = new DateTime(2021, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        },
                        new
                        {
                            MaCB = "CB09",
                            GiaVe = 1000000m,
                            MaSB_Den = "SB10",
                            MaSB_Di = "SB09",
                            NgayGio = new DateTime(2021, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianBay = 120
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBayHangVe", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHV", "MaCB");

                    b.HasIndex("MaCB");

                    b.ToTable("ChuyenBayHangVes");

                    b.HasData(
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB01",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB01",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB02",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB02",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB03",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB03",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB04",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB04",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB05",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB05",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB06",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB06",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB07",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB07",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB08",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB08",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV01",
                            MaCB = "CB09",
                            SoLuong = 50
                        },
                        new
                        {
                            MaHV = "HV02",
                            MaCB = "CB09",
                            SoLuong = 50
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.HangVe", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TiLe_Gia")
                        .HasColumnType("float");

                    b.HasKey("MaHV");

                    b.ToTable("HangVes");

                    b.HasData(
                        new
                        {
                            MaHV = "HV01",
                            TenHV = "Hang thuong gia",
                            TiLe_Gia = 1.5
                        },
                        new
                        {
                            MaHV = "HV02",
                            TenHV = "Hang pho thong",
                            TiLe_Gia = 1.0
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            MaKH = "KH01",
                            CMND = "123456789",
                            SDT = "0123456780",
                            TenKH = "Nguyen Van A"
                        },
                        new
                        {
                            MaKH = "KH02",
                            CMND = "987654321",
                            SDT = "0123456781",
                            TenKH = "Nguyen Van B"
                        },
                        new
                        {
                            MaKH = "KH03",
                            CMND = "456789123",
                            SDT = "0123456782",
                            TenKH = "Nguyen Van C"
                        },
                        new
                        {
                            MaKH = "KH04",
                            CMND = "321654987",
                            SDT = "0123456783",
                            TenKH = "Nguyen Van D"
                        },
                        new
                        {
                            MaKH = "KH05",
                            CMND = "789123456",
                            SDT = "0123456784",
                            TenKH = "Nguyen Van E"
                        },
                        new
                        {
                            MaKH = "KH06",
                            CMND = "654987321",
                            SDT = "0123456785",
                            TenKH = "Nguyen Van F"
                        },
                        new
                        {
                            MaKH = "KH07",
                            CMND = "123789456",
                            SDT = "0123456786",
                            TenKH = "Nguyen Van G"
                        },
                        new
                        {
                            MaKH = "KH08",
                            CMND = "987123654",
                            SDT = "0123456787",
                            TenKH = "Nguyen Van H"
                        },
                        new
                        {
                            MaKH = "KH09",
                            CMND = "456123789",
                            SDT = "0123456788",
                            TenKH = "Nguyen Van I"
                        },
                        new
                        {
                            MaKH = "KH10",
                            CMND = "321987654",
                            SDT = "0123456789",
                            TenKH = "Nguyen Van K"
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.QuyDinhChung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ThoiGianChamNhatDatVe")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianHuyDatVe")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("QuyDinhChungs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ThoiGianChamNhatDatVe = 30,
                            ThoiGianHuyDatVe = 3
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBay", b =>
                {
                    b.Property<string>("MaSB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TGDungMax")
                        .HasColumnType("int");

                    b.Property<int>("TGDungMin")
                        .HasColumnType("int");

                    b.Property<string>("TenSB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSB");

                    b.ToTable("SanBays");

                    b.HasData(
                        new
                        {
                            MaSB = "SB01",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Noi Bai",
                            ViTri = "Ha Noi"
                        },
                        new
                        {
                            MaSB = "SB02",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Tan Son Nhat",
                            ViTri = "Ho Chi Minh"
                        },
                        new
                        {
                            MaSB = "SB03",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Da Nang",
                            ViTri = "Da Nang"
                        },
                        new
                        {
                            MaSB = "SB04",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Cam Ranh",
                            ViTri = "Khanh Hoa"
                        },
                        new
                        {
                            MaSB = "SB05",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Phu Quoc",
                            ViTri = "Kien Giang"
                        },
                        new
                        {
                            MaSB = "SB06",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Can Tho",
                            ViTri = "Can Tho"
                        },
                        new
                        {
                            MaSB = "SB07",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Buon Ma Thuot",
                            ViTri = "Dak Lak"
                        },
                        new
                        {
                            MaSB = "SB08",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Pleiku",
                            ViTri = "Gia Lai"
                        },
                        new
                        {
                            MaSB = "SB09",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Vinh",
                            ViTri = "Nghe An"
                        },
                        new
                        {
                            MaSB = "SB10",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Hue",
                            ViTri = "Thua Thien Hue"
                        },
                        new
                        {
                            MaSB = "SB11",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Hai Phong",
                            ViTri = "Hai Phong"
                        },
                        new
                        {
                            MaSB = "SB12",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Dong Hoi",
                            ViTri = "Quang Binh"
                        },
                        new
                        {
                            MaSB = "SB13",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Rach Gia",
                            ViTri = "Kien Giang"
                        },
                        new
                        {
                            MaSB = "SB14",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Con Dao",
                            ViTri = "Ba Ria - Vung Tau"
                        },
                        new
                        {
                            MaSB = "SB15",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Ca Mau",
                            ViTri = "Ca Mau"
                        },
                        new
                        {
                            MaSB = "SB16",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Quy Nhon",
                            ViTri = "Binh Dinh"
                        },
                        new
                        {
                            MaSB = "SB17",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Tuy Hoa",
                            ViTri = "Phu Yen"
                        },
                        new
                        {
                            MaSB = "SB18",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Phu Cat",
                            ViTri = "Binh Dinh"
                        },
                        new
                        {
                            MaSB = "SB19",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Dien Bien",
                            ViTri = "Dien Bien"
                        },
                        new
                        {
                            MaSB = "SB20",
                            TGDungMax = 60,
                            TGDungMin = 30,
                            TenSB = "Chu Lai",
                            ViTri = "Quảng nam"
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBayTrungGian", b =>
                {
                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TGDung")
                        .HasColumnType("int");

                    b.HasKey("MaCB", "MaSB");

                    b.HasIndex("MaSB");

                    b.ToTable("SanBayTrungGians");

                    b.HasData(
                        new
                        {
                            MaCB = "CB01",
                            MaSB = "SB01",
                            GhiChu = "Ghi chu 1",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB01",
                            MaSB = "SB02",
                            GhiChu = "Ghi chu 2",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB02",
                            MaSB = "SB02",
                            GhiChu = "Ghi chu 3",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB02",
                            MaSB = "SB03",
                            GhiChu = "Ghi chu 4",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB03",
                            MaSB = "SB03",
                            GhiChu = "Ghi chu 5",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB03",
                            MaSB = "SB04",
                            GhiChu = "Ghi chu 6",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB04",
                            MaSB = "SB04",
                            GhiChu = "Ghi chu 7",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB04",
                            MaSB = "SB05",
                            GhiChu = "Ghi chu 8",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB05",
                            MaSB = "SB05",
                            GhiChu = "Ghi chu 9",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB05",
                            MaSB = "SB06",
                            GhiChu = "Ghi chu 10",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB06",
                            MaSB = "SB06",
                            GhiChu = "Ghi chu 11",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB06",
                            MaSB = "SB07",
                            GhiChu = "Ghi chu 12",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB07",
                            MaSB = "SB07",
                            GhiChu = "Ghi chu 13",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB07",
                            MaSB = "SB08",
                            GhiChu = "Ghi chu 14",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB08",
                            MaSB = "SB08",
                            GhiChu = "Ghi chu 15",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB08",
                            MaSB = "SB09",
                            GhiChu = "Ghi chu 16",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB09",
                            MaSB = "SB09",
                            GhiChu = "Ghi chu 17",
                            TGDung = 45
                        },
                        new
                        {
                            MaCB = "CB09",
                            MaSB = "SB10",
                            GhiChu = "Ghi chu 18",
                            TGDung = 45
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SoSanBayDung", b =>
                {
                    b.Property<string>("MaSanBayDi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSanBayDen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoSBDung_Max")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianBayToiThieu")
                        .HasColumnType("int");

                    b.HasKey("MaSanBayDi", "MaSanBayDen");

                    b.ToTable("SoSanBayDungs");

                    b.HasData(
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB02",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB03",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB04",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB05",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB06",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB07",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB08",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB09",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB01",
                            MaSanBayDen = "SB10",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB02",
                            MaSanBayDen = "SB03",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB02",
                            MaSanBayDen = "SB04",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB02",
                            MaSanBayDen = "SB05",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        },
                        new
                        {
                            MaSanBayDi = "SB02",
                            MaSanBayDen = "SB06",
                            SoSBDung_Max = 1,
                            ThoiGianBayToiThieu = 120
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.VeMayBay", b =>
                {
                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaCB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVe");

                    b.HasIndex("MaCB");

                    b.HasIndex("MaHV");

                    b.HasIndex("MaKH");

                    b.ToTable("VeMayBays");

                    b.HasData(
                        new
                        {
                            MaVe = "VMB01",
                            GiaTien = 1500000m,
                            MaCB = "CB01",
                            MaHV = "HV01",
                            MaKH = "KH01",
                            NgayDat = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayMua = new DateTime(2021, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã mua"
                        },
                        new
                        {
                            MaVe = "VMB02",
                            GiaTien = 1000000m,
                            MaCB = "CB01",
                            MaHV = "HV02",
                            MaKH = "KH02",
                            NgayDat = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Chưa Thanh Toán"
                        },
                        new
                        {
                            MaVe = "VMB03",
                            GiaTien = 1500000m,
                            MaCB = "CB02",
                            MaHV = "HV01",
                            MaKH = "KH03",
                            NgayDat = new DateTime(2021, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayMua = new DateTime(2021, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã mua"
                        },
                        new
                        {
                            MaVe = "VMB04",
                            GiaTien = 1000000m,
                            MaCB = "CB02",
                            MaHV = "HV02",
                            MaKH = "KH04",
                            NgayDat = new DateTime(2021, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Chưa Thanh Toán"
                        },
                        new
                        {
                            MaVe = "VMB05",
                            GiaTien = 1500000m,
                            MaCB = "CB03",
                            MaHV = "HV01",
                            MaKH = "KH05",
                            NgayDat = new DateTime(2021, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayMua = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã mua"
                        },
                        new
                        {
                            MaVe = "VMB06",
                            GiaTien = 1000000m,
                            MaCB = "CB03",
                            MaHV = "HV02",
                            MaKH = "KH06",
                            NgayDat = new DateTime(2021, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Chưa Thanh Toán"
                        },
                        new
                        {
                            MaVe = "VMB07",
                            GiaTien = 1500000m,
                            MaCB = "CB04",
                            MaHV = "HV01",
                            MaKH = "KH07",
                            NgayDat = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayMua = new DateTime(2021, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã mua"
                        },
                        new
                        {
                            MaVe = "VMB08",
                            GiaTien = 1000000m,
                            MaCB = "CB04",
                            MaHV = "HV02",
                            MaKH = "KH08",
                            NgayDat = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Chưa Thanh Toán"
                        });
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBayHangVe", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("ChuyenBayHangVes")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.HangVe", "HangVe")
                        .WithMany("ChuyenBayHangVes")
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("HangVe");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBayTrungGian", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("SanBayTrungGians")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.SanBay", "SanBay")
                        .WithMany("SanBayTrungGians")
                        .HasForeignKey("MaSB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("SanBay");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.VeMayBay", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("VeMayBays")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.HangVe", "HangVe")
                        .WithMany("VeMayBays")
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.KhachHang", "KhachHang")
                        .WithMany("VeMayBays")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("HangVe");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBay", b =>
                {
                    b.Navigation("ChuyenBayHangVes");

                    b.Navigation("SanBayTrungGians");

                    b.Navigation("VeMayBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.HangVe", b =>
                {
                    b.Navigation("ChuyenBayHangVes");

                    b.Navigation("VeMayBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.KhachHang", b =>
                {
                    b.Navigation("VeMayBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBay", b =>
                {
                    b.Navigation("SanBayTrungGians");
                });
#pragma warning restore 612, 618
        }
    }
}
