// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE104_AirlineTicketManage.Server.Data;

#nullable disable

namespace SE104_AirlineTicketManage.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBay", b =>
                {
                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSB_Den")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSB_Di")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianBay")
                        .HasColumnType("int");

                    b.HasKey("MaCB");

                    b.ToTable("ChuyenBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBayHangVe", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHV", "MaCB");

                    b.HasIndex("MaCB");

                    b.ToTable("ChuyenBayHangVes");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.HangVe", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TiLe_Gia")
                        .HasColumnType("float");

                    b.HasKey("MaHV");

                    b.ToTable("HangVes");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.QuyDinhChung", b =>
                {
                    b.Property<int>("ThoiGianChamNhatDatVe")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianHuyDatVe")
                        .HasColumnType("int");

                    b.ToTable("QuyDinhChungs");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBay", b =>
                {
                    b.Property<string>("MaSB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TGDungMax")
                        .HasColumnType("int");

                    b.Property<int>("TGDungMin")
                        .HasColumnType("int");

                    b.Property<string>("TenSB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSB");

                    b.ToTable("SanBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBayTrungGian", b =>
                {
                    b.Property<string>("MaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TGDung")
                        .HasColumnType("int");

                    b.HasKey("MaCB", "MaSB");

                    b.HasIndex("MaSB");

                    b.ToTable("SanBayTrungGians");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SoSanBayDung", b =>
                {
                    b.Property<string>("MaSanBayDi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSanBayDen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SanBay_DenMaSB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SanBay_DiMaSB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoSBDung_Max")
                        .HasColumnType("int");

                    b.HasKey("MaSanBayDi", "MaSanBayDen");

                    b.HasIndex("SanBay_DenMaSB");

                    b.HasIndex("SanBay_DiMaSB");

                    b.ToTable("SoSanBayDungs");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.VeMayBay", b =>
                {
                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChuyenBayMaCB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HangVeMaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangMaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVe");

                    b.HasIndex("ChuyenBayMaCB");

                    b.HasIndex("HangVeMaHV");

                    b.HasIndex("KhachHangMaKH");

                    b.ToTable("VeMayBays");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBayHangVe", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("ChuyenBayHangVes")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.HangVe", "HangVe")
                        .WithMany("ChuyenBayHangVes")
                        .HasForeignKey("MaHV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("HangVe");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBayTrungGian", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany("SanBayTrungGians")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.SanBay", "SanBay")
                        .WithMany("SanBayTrungGians")
                        .HasForeignKey("MaSB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("SanBay");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SoSanBayDung", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.SanBay", "SanBay_Den")
                        .WithMany()
                        .HasForeignKey("SanBay_DenMaSB");

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.SanBay", "SanBay_Di")
                        .WithMany()
                        .HasForeignKey("SanBay_DiMaSB");

                    b.Navigation("SanBay_Den");

                    b.Navigation("SanBay_Di");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.VeMayBay", b =>
                {
                    b.HasOne("SE104_AirlineTicketManage.Server.Models.ChuyenBay", "ChuyenBay")
                        .WithMany()
                        .HasForeignKey("ChuyenBayMaCB");

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.HangVe", "HangVe")
                        .WithMany()
                        .HasForeignKey("HangVeMaHV");

                    b.HasOne("SE104_AirlineTicketManage.Server.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMaKH");

                    b.Navigation("ChuyenBay");

                    b.Navigation("HangVe");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.ChuyenBay", b =>
                {
                    b.Navigation("ChuyenBayHangVes");

                    b.Navigation("SanBayTrungGians");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.HangVe", b =>
                {
                    b.Navigation("ChuyenBayHangVes");
                });

            modelBuilder.Entity("SE104_AirlineTicketManage.Server.Models.SanBay", b =>
                {
                    b.Navigation("SanBayTrungGians");
                });
#pragma warning restore 612, 618
        }
    }
}
